steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/video-processor', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/video-processor']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'video-processor'
      - '--image'
      - 'gcr.io/$PROJECT_ID/video-processor'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
